### PR TITLE
Fix/3259 mobile top nav group title looks clickable

### LINKED ISSUE #2690: [ic-top-navigation] - Landmark-unique accessibility violation
## Summary of the bug 
There is a landmark-unique accessibility violation when the top navigation menu is opened in mobile mode and the menu contains more than one navigation group.

## 🪜 How to reproduce 
1. Open a top navigation menu in mobile mode that contains more than one ic-navigation-group
2. Run accessibility fast pass
or
4. Run the a11y tests within that are currently commented out within IcNavigationMenu Cypress test file

## 📸 Screenshots or code 
Impacted area highlighted:
image

Details from storybook accessibility tab:
image

## 🧐 Expected behaviour 
There should be no accessibility violations.

## Additional info 
Two a11y tests within Ic-Navigation-menu.cy.tsx should be uncommented when resolved.

### PR DESCRIPTION
**Pull request by GCHQ-Developer-847**
## Summary of the changes
To test the changes, look at the "Default" or "Long content" side nav stories and the "With grouped navigation" top nav story.

- Updated nav groups to use a `<div>` instead of a button when not expandable plus updated hover + active styling
- When a side nav is collapsed, nav groups which are not expandable are now not displayed; previously it was just showing a large gap so thought this solution made sense (created a ticket to get this updated on Figma: [#3389](https://github.com/mi6/ic-ui-kit/issues/3389))
- Updated nav groups to make long titles wrap instead of overflow - included updating some styling e.g. padding, so that nav groups now match the Figma designs more closely
- Add aria-labelledby to nav groups to resolve a11y error I was getting about multiple `<nav>`s which aren't unique
<br />

UPDATE: IcNavigationMenu Cypress tests updated further - removed skipped tests about focussing on non-expandable nav groups (now no longer expected to receive focus), and uncommented a11y checks. Realised this PR will resolve #2690 and #2697 as well (will close these once merged).

## Related issue
#3259 plus fixes for other small issues noticed

### General 

- [x] Changes to docs package checked and committed.
- [x] All acceptance criteria reviewed and met. 

### Testing

- [x] Relevant unit tests and visual regression tests added. 
- [x] Visual testing against Figma component specification completed. 
- [x] Playground stories in React Storybook up to date, with any prop changes and additions addressed. 
- [x] Compare performance of modified components against develop using Performance addon in React Storybook.

### Accessibility 

- [x] Accessibility Insights FastPass performed.
- [x] A11y unit test added and yields no issues.
- [x] A11y plug-in on Storybook yields no issues. 
- [x] Manual screen reader testing performed using NVDA and VoiceOver. 
- [x] Manual keyboard testing for keyboard controls and logical focus order. 
- [x] Correct roles used and ARIA attributes used correctly where required. 
- [x] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 

### Resize/zoom behaviour 

- [x] Page can be zoomed to 400% with no loss of content. 
- [x] Screen magnifier used with no issues. 
- [x] Text resized to 200% with no loss of content.
- [x] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.

### System modes

- [x] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [x] Windows High Contrast mode tested with no loss of content.
- [x] System light and dark mode tested with no loss of content.
- [x] Browser support tested (Chrome, Safari, Firefox and Edge). 

### Testing content extremes

- [x] Min/max content examples tested with no loss of content or overflow. 
- [x] All prop combinations work without issue. 
- [x] Tested for FOUC (Flash of Unstyled Content) in both SSR (Server-Side Rendering) and SSG (Static Site Generation) settings.
- [x] Controlled and uncontrolled input components tested.
- [x] Props/slots can be updated after initial render.

### CODE REVIEW

**Comment by GCHQ-Developer-847** [comment]
[Web components build](https://mi6.github.io/ic-ui-kit/branches/fix/3259-mobile-top-nav-group-title-looks-clickable/web-components/?path=/docs/web-components-accordion--docs)
[React build](https://mi6.github.io/ic-ui-kit/branches/fix/3259-mobile-top-nav-group-title-looks-clickable/react/?path=/docs/react-components-accordion--docs)

**Comment by GCHQ-Developer-847** [comment]
Just fixing the conflicts with the visual test screenshots

**Comment by GCHQ-Developer-847** [comment]
Just sorting out conflicts with the visual test screenshots

**Review by GCHQ-Developer-530 — APPROVED** [review]

File: packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx [hunk 1]
```diff
@@ -481,53 +501,47 @@ export class NavigationGroup {
           "ic-navigation-group-collapsed": !this.expanded,
           ["ic-navigation-group-side-nav"]: this.navigationType === "side",
           [`ic-theme-${this.theme}`]: this.theme !== "inherit",
+          ["expandable"]: !!expandable,
```
Comment (ad9242) [inline packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx:504]: minor on, but should this be made more unique (eg include the component name : `ic-navigation-group-expandable`). we previously changed class names applied on the host, so there is less risk of clashing with names users may apply

**Review by ad9242 — CHANGES_REQUESTED** [review]

File: packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx (hunk 1 above)
Comment (GCHQ-Developer-847) [reply packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx]: Sorted 👍

**Comment by GCHQ-Developer-847** [comment]
Just sorting out the failing visual tests

**Comment by GCHQ-Developer-847** [comment]
All ready for review again now

**Review by GCHQ-Developer-530 — APPROVED** [review]

**Review by ad9242 — APPROVED** [review]
